---
- name: Install Docker and related packages
  hosts: localhost
  become: true

  vars:
    release: "{{ ansible_distribution_release }}"
    version: "{{ ansible_distribution_version }}"

  tasks:
    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release }} stable
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - containerd.io
          - docker-ce
          - docker-ce-cli
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      register: apt_install

    - name: Print install status
      ansible.builtin.debug:
        var: apt_install
