---
- name: Install VS NVM & LTS Node.js
  hosts: localhost

  tasks:
    - name: Download nvm install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh
        dest: /tmp/install_nvm.sh
        mode: "0755"

    - name: Install nvm
      ansible.builtin.shell: >
        bash /tmp/install_nvm.sh
      args:
        creates: /home/{{ ansible_env.USER }}/.nvm/nvm.sh

    - name: Install lts node
      ansible.builtin.shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node/{{ item }}"
      loop:
        - --lts
      register: node_install

    - name: Print install status
      ansible.builtin.debug:
        var: node_install
